name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # rama principal
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      # Si tu sitio está hecho en HTML, no necesitas build adicional.
      # Si usas Jekyll, Hugo o un generador, agrega los pasos aquí.
      # Por ejemplo (solo si tienes un build):
      # - name: Construir sitio
      #   run: |
      #     npm install
      #     npm run build

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'  # Carpeta raíz o la de salida de tu build (dist/, public/, etc.)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
